name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true

# -----------------------------------------------------------------------------

# favicon: static/favicon.png

# # -----------------------------------------------------------------------------

# branding:
#   title: Discotips                 # Your custom website title; keep it short.
#   logo: static/logo.png          # Path to a logo file.
#   logoAlign: right               # Align the logo to the right or the left.
#   label: Docs # Optional label. To remove the label, remove this config.
#   colors:
#     label:                  # Label colors
#       text: "#ffffff"       # Custom color for the label text.
#       background: "#ff0000" # Custom color for the label background.

# # -----------------------------------------------------------------------------
# # -----------------------------------------------------------------------------

# footer:
#   copyright: "Discortips - Site non affilié à Discord" # A custom copyright statement.
#   links:               # A list of links to include in the footer.
#                        # See also: links
#     - text: Serveur Support    # The text to use for the link
#       link: https://discord.gg/VmbdqukC8n # Point to an internal file or external URL.

# -----------------------------------------------------------------------------
